// ─────────────────────────────────────────────────────────────────────────────
// Shared entity shapes. The single source of truth that frontend, API, and data
// layer all import from. Any change here is a 3-person review.
// ─────────────────────────────────────────────────────────────────────────────

export type Availability = "full-time" | "fractional" | "advisory" | "internship";
export type Compensation = "cash" | "equity" | "mentor";
export type Stage = "pre-seed" | "seed" | "series-a" | "series-b" | "growth";

export type Sector =
  | "life-sciences"
  | "ai"
  | "defense-aerospace"
  | "cyber"
  | "energy"
  | "advanced-manufacturing"
  | "fintech"
  | "software";

export type Origin =
  | "u-of-u-spinout"
  | "byu-spinout"
  | "usu-spinout"
  | "bootstrapped"
  | "vc-backed";

export type StartupNeed =
  | "ceo"
  | "cto"
  | "biz-dev"
  | "regulatory"
  | "sales-lead"
  | "engineering"
  | "marketing";

export type UtahOrgType =
  | "tto"
  | "accelerator"
  | "university"
  | "community"
  | "investor";

export interface UtahOrgRef {
  id: string;
  name: string;
  type: UtahOrgType;
  /** Linked universities, e.g. ["u-of-u"] for PIVOT Center */
  universities?: string[];
}

export interface TalentDTO {
  id: string;
  name: string;
  email: string;
  headline: string;
  bio: string;
  /**
   * Free-text answer to "what are you mainly looking for?" — explicit intent
   * separate from the biographical bio. This drives the embedding heavily so
   * matches reflect what the person *wants*, not just who they are.
   */
  lookingFor?: string;
  skills: string[];
  domains: Sector[];
  availability: Availability;
  compensation: Compensation[];
  stagePrefs: Stage[];
  riskTolerance: 1 | 2 | 3 | 4 | 5;
  location: string;
  utahOrgs: UtahOrgRef[];
  /** Avatar — http(s) URL or `data:` URL from a recent file upload. */
  photoUrl?: string;
  linkedinUrl?: string;
  xUrl?: string;
  createdAt: string;
}

export interface StartupDTO {
  id: string;
  name: string;
  oneLiner: string;
  description: string;
  sector: Sector;
  origin: Origin;
  /** Technology Readiness Level, 1–9. Optional because not every startup self-classifies. */
  trl?: number;
  fundingStage: Stage;
  fundingStatus: "grant" | "pre-revenue" | "revenue";
  needs: StartupNeed[];
  location: string;
  utahOrgs: UtahOrgRef[];
  /** Logo image URL (or `data:` URL). Falls back to a letter-mark in the UI. */
  logoUrl?: string;
  linkedinUrl?: string;
  xUrl?: string;
  websiteUrl?: string;
  createdAt: string;
}

export interface MatchFactors {
  skillFit: string;
  stageFit: string;
  utahSignal: string;
  /** Required. Hiding weaknesses makes matches look like a sales pitch. */
  concerns: string;
}

export type Verdict = "strong" | "good" | "partial";

export interface RankedMatch<T = TalentDTO | StartupDTO> {
  candidateId: string;
  candidate: T;
  /** 0..1 final score (LLM rerank score + capped proximity boost) */
  score: number;
  verdict: Verdict;
  /** One paragraph, generated by the LLM (or templated by the mock). */
  reason: string;
  factors: MatchFactors;
  /** Utah-ecosystem bonus added on top of the LLM score, capped at 0.25 */
  proximityBoost: number;
  proximityReasons: string[];
}

export interface PipelineTimings {
  gates: number;
  vector: number;
  rerank: number;
  /** True if the result was served from MatchCache instead of being recomputed. */
  cacheHit?: boolean;
}

export interface MatchResponse {
  matches: RankedMatch[];
  pipelineMs: PipelineTimings;
}

export type InterestSide = "talent" | "startup";
export type InterestVote = "pending" | "interested" | "pass";

export interface InterestState {
  talentId: string;
  startupId: string;
  talentState: InterestVote;
  startupState: InterestVote;
  /** ISO timestamp set the moment both sides have flipped to "interested". */
  mutualAt: string | null;
}

export type NotificationKind = "interest_received" | "mutual_match";

export interface NotificationDTO {
  id: string;
  recipientId: string;
  recipientType: InterestSide;
  kind: NotificationKind;
  fromId: string;
  fromName: string;
  fromType: InterestSide;
  /** One-line summary shown in the dropdown row. */
  message: string;
  /** Where to send the user when the row is clicked. */
  href: string;
  createdAt: string;
  /** ISO timestamp when this notification was marked read; null if unread. */
  readAt: string | null;
}

export interface AffinityPushPayload {
  talent: { name: string; email: string };
  startup: { name: string };
  listName: string;
  note: string;
  factors: MatchFactors;
  proximityReasons: string[];
}
